# =============================================================================
# api-deployment.yaml — API FastAPI no cluster Kind.
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cloudtask
  labels: { app: api, component: backend }
spec:
  replicas: 2
  selector:
    matchLabels: { app: api }
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: { app: api, component: backend }
    spec:
      # InitContainer para garantir que o Postgres esteja aceitando conexões
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - >-
              until pg_isready -h postgres -p 5432 -U "$POSTGRES_USER";
              do echo "esperando postgres..."; sleep 2; done;
              echo "postgres pronto."
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: cloudtask-secrets, key: POSTGRES_USER }
      containers:
        - name: api
          image: cloudtask-api:prod
          imagePullPolicy: IfNotPresent
          
          # REMOVA O SLEEP E USE O COMANDO DA API:
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          
          env:
            - name: PYTHONPATH
              value: "/app"
          envFrom:
            - configMapRef: { name: cloudtask-config }
            - secretRef: { name: cloudtask-secrets }
          ports:
            - containerPort: 8000
              name: http
          
          # Probes de Saúde
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15

          # Recursos definidos para o container
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }