apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudtask-config
  namespace: cloudtask
data:
  POSTGRES_DB: "cloudtask"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  STORAGE_MODE: "local"
  LOCAL_UPLOADS_DIR: "./local_uploads"