apiVersion: v1
kind: Secret
metadata:
  name: cloudtask-secrets
  namespace: cloudtask
type: Opaque
data:
  POSTGRES_USER: "Y2xvdWR0YXNr" 
  POSTGRES_PASSWORD: "U2VuaGFTZWd1cmExMjMh" 
  SECRET_KEY: "c3VwZXItc2VjcmV0LWtleS0xMjM=" 
  DATABASE_URL: "cG9zdGdyZXNxbDovL2Nsb3VkdGFzazpTZW5oYVNlZ3VyYTEyMyFAcG9zdGdyZXM6NTQzMi9jbG91ZHRhc2s="
  
  # Adicione aqui os valores convertidos:
  AWS_ACCESS_KEY_ID: "U1VBX0FDQ0VTU19LRVk="
  AWS_SECRET_ACCESS_KEY: "U1VBX1NFQ1JFVF9LRVk="
  AWS_SESSION_TOKEN: "U0VVX1NFU1NJT05fVE9LRU4="